url: "https://irikas.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Irika Sinha" # the name of your site, e.g. ACME Corp.
description: "Leveraging bioinformatics to investigate neurodegeneration"
